### ISSUE TITLE
Error building on Android: No file or variants found for asset: packages/twitch_chat/.env.

### ISSUE THREAD

**Issue by w3cj** [LezdCS/twitch_chat#7]
Ran into this error trying to build for Android on a Mac today:

```sh
Error detected in pubspec.yaml:
No file or variants found for asset: packages/twitch_chat/.env.

This asset was included from package twitch_chat.
Target debug_android_application failed: Exception: Failed to bundle asset files.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/path/to/flutter/bin/flutter'' finished with non-zero exit value 1
```

To fix it I had to manually create a `.env` file in the pub cache at `/Users/<username>/.pub-cache/hosted/pub.dev/twitch_chat-0.0.4`

Apparently the [`.env`](https://github.com/LezdCS/twitch_chat/blob/main/pubspec.yaml#L34) file is no longer included in your package when installing from pub.dev

**Comment by alanfortlink** [comment]
Adding some info...

According to https://dart.dev/tools/pub/publishing#what-files-are-published, hidden files will not be published.
From the list of things that won't make it to pub.dev:
```
Any hidden files or directories—that is, files with names that begin with dot (.)
```

**Comment by LezdCS** [comment]
Sorry for missing the issue. Thanks, I will remove the needs of the .env for the testing environnment in the next update. The workaround for now would be to install the package like this in your project: 
```
twitch_chat:
    git:
        url: https://github.com/LezdCS/twitch_chat.git
```

**Comment by LezdCS** [comment]
Should be fixed on 

> twitch_chat: ^1.0.0
